:verbose: false
:concurrency: 5
:pidfile: ./tmp/pids/sidekiq.pid
:queues:
  - default
:redis:
  :url: "rediss://red-cp5nvsa1hbls73fj3ssg:9ocnNmDZK6fPz4UChUI3wfF8AukSP0oU@virginia-redis.render.com:6379"
